version: '3'
services:
  bot:
    build: ./
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=redis
    command:
      bot

  web:
    build: ./
    environment:
      - NODE_ENV=production
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - REDIS_HOST=redis
    ports:
      - 80:4500
    command:
      web

  redis:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - redisdata:/data
volumes:
  redisdata:
    driver: "local"
